name: Generate README

on:
  push:
    paths:
      - 'papers/**'
      - 'generate_readme.py'
      - 'category_info.json'

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Run Python script
      run: python generate_readme.py
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Generate README"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
